<?php
/**
 * @file
 * Code for the Ding Latto Frontend feature.
 */

include_once 'ding_oc_latto_frontend.features.inc';

/**
 * Implements hook_page_manager_load_task_handlers_alter().
 *
 * When page manager loads task handlers for pages we remove the page handlers
 * that are handled by features in this module.
 *
 * Requires a patch to ctools/page_manager.module (call drupal_alter).
 */
function ding_oc_latto_frontend_page_manager_load_task_handlers_alter(&$handlers, $task, $subtask_id = NULL) {
  // If we are on an admin/structure/features* page or we are being called
  // through drush features we will filter out page handlers.
  $in_drush_features = FALSE;

  if (function_exists('drush_get_command')) {
    $command = drush_get_command();
    if (isset($command['drupal dependencies']) && in_array('features', $command['drupal dependencies'])) {
      $in_drush_features = TRUE;
    }
  };

  if (preg_match('/admin\/structure\/features/', $_GET['q']) || $in_drush_features) {
    // Load the page handlers handled by this feature module.
    $ding_oc_latto_frontend_handlers = array_keys(ding_oc_latto_frontend_default_page_manager_handlers());

    if ($task['name'] == 'page') {
      foreach ($handlers as $handler) {
        if (in_array($handler->name, $ding_oc_latto_frontend_handlers)) {
          unset($handlers[$handler->name]);
        }
      }
    }
  }
}

/**
 * Implements hook_menu_block_blocks().
 */
function ding_oc_latto_frontend_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'ding_oc_latto_frontend-1' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Menu block main',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 1,
      'expanded'    => 0,
      'sort'        => 0,
    ),
    'ding_oc_latto_frontend-2' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => '',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 0,
      'expanded'    => 0,
      'sort'        => 0,
    ),
    'ding_oc_latto_frontend-3' => array(
      'menu_name'   => 'menu-footer-menu-2',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Netbiblioteket menu block',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 1,
      'expanded'    => 0,
      'sort'        => 0,
    ),
    'ding_oc_latto_frontend-4' => array(
      'menu_name'   => 'menu-footer-menu-4',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'om biblioteket menu block',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 1,
      'expanded'    => 0,
      'sort'        => 0,
    ),
    'ding_oc_latto_frontend-5' => array(
      'menu_name'   => 'menu-footer-menu-3',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'om hjemmesiden menu block',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 1,
      'expanded'    => 0,
      'sort'        => 0,
    ),
    'ding_oc_latto_frontend-6' => array(
      'menu_name'   => 'menu-footer-menu-1',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'tilbudet fra biblioteket menu block',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 1,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}
